CREATE OR REPLACE DATABASE marvel_akinator;
USE marvel;

-- Tabla para almacenar las preguntas y personajes
CREATE TABLE nodes (
   id INT AUTO_INCREMENT PRIMARY KEY,
   pregunta TEXT,
   personaje VARCHAR(255),
   parent_id INT,
   izquierdo_id INT,
   derecho_id INT
);

INSERT INTO nodes (pregunta, personaje, parent_id, izquierdo_id, derecho_id) VALUES
    ('¿Es de Marvel?', NULL, NULL, 2, 3),
    ('¿Pertenece a los Vengadores?', NULL, 1, 4, 5),
    ('¿Es un mutante?', NULL, 1, 6, 7),
    ('¿Usa un traje de alta tecnología?', NULL, 2, 8, 9),
    ('¿Es un soldado?', NULL, 2, 10, 11),
    ('¿Tiene habilidades sobrehumanas?', NULL, 3, 12, 13),
    ('¿Puede manipular el metal?', NULL, 3, 14, 15),
    ('¿Es extremadamente rápido?', NULL, 4, 16, 17),
    ('¿Puede volar?', NULL, 4, 18, 19),
    ('¿Es parte de los X-Men?', NULL, 5, 20, 21),
    ('¿Es parte de los Cuatro Fantásticos?', NULL, 5, 22, 23),
    ('¿Tiene poderes mágicos?', NULL, 6, 24, 25),
    ('¿Es una deidad?', NULL, 6, 26, 27),
    ('¿Puede cambiar de forma?', NULL, 7, 28, 29),
    ('¿Tiene habilidades psíquicas?', NULL, 7, 30, 31),
    ('¿Es un espía?', NULL, 8, 32, 33),
    ('¿Es un alienígena?', NULL, 8, 34, 35),
    ('¿Tiene fuerza sobrehumana?', NULL, 9, 36, 37),
    ('¿Es inmortal?', NULL, 9, 38, 39),
    ('¿Tiene habilidades tecnológicas avanzadas?', NULL, 10, 40, 41),
    ('¿Es un experto en combate?', NULL, 10, 42, 43),
    ('¿Puede controlar el clima?', NULL, 11, 44, 45),
    ('¿Es un experto en artes marciales?', NULL, 11, 46, 47),
    ('¿Es conocido por su inteligencia?', NULL, 12, 48, 49),
    ('¿Puede teletransportarse?', NULL, 12, 50, 51),
    ('¿Es de origen místico?', NULL, 13, 52, 53),
    ('¿Pertenece a un equipo?', NULL, 13, 54, 55),
    ('¿Es resistente a las balas?', NULL, 14, 56, 57),
    ('¿Es un mercenario?', NULL, 14, 58, 59),
    ('¿Tiene habilidades curativas?', NULL, 15, 60, 61),
    ('¿Es inmune al veneno?', NULL, 15, 62, 63),
    ('¿Usa una máscara?', NULL, 16, 64, 65),
    ('¿Es un villano recurrente?', NULL, 16, 66, 67),
    ('¿Es un investigador?', NULL, 17, 68, 69),
    ('¿Es un miembro de la familia real?', NULL, 17, 70, 71),
    ('¿Tiene la habilidad de volverse invisible?', NULL, 18, 72, 73),
    ('¿Puede manipular la realidad?', NULL, 18, 74, 75),
    ('¿Es un cazador?', NULL, 19, 76, 77),
    ('¿Usa armas avanzadas?', NULL, 19, 78, 79);

INSERT INTO nodes (pregunta, personaje, parent_id) VALUES
    (NULL, 'Iron Man', 32),
    (NULL, 'War Machine', 32),
    (NULL, 'Captain America', 33),
    (NULL, 'Black Widow', 33),
    (NULL, 'Doctor Strange', 34),
    (NULL, 'Scarlet Witch', 34),
    (NULL, 'Nick Fury', 35),
    (NULL, 'Maria Hill', 35),
    (NULL, 'Thanos', 36),
    (NULL, 'Loki', 36),
    (NULL, 'Mystique', 37),
    (NULL, 'Skrull', 37),
    (NULL, 'Professor X', 38),
    (NULL, 'Magneto', 38),
    (NULL, 'Hulk', 39),
    (NULL, 'Thor', 39),
    (NULL, 'Hawkeye', 40),
    (NULL, 'Falcon', 40),
    (NULL, 'Wolverine', 41),
    (NULL, 'Deadpool', 41),
    (NULL, 'Storm', 42),
    (NULL, 'Jean Grey', 42),
    (NULL, 'Beast', 43),
    (NULL, 'Cyclops', 43),
    (NULL, 'Human Torch', 44),
    (NULL, 'Invisible Woman', 44),
    (NULL,  'Mr. Fantastic', 45),
    (NULL, 'The Thing', 45),
    (NULL, 'Silver Surfer', 46),
    (NULL, 'Galactus', 46),
    (NULL, 'Black Panther', 47),
    (NULL, 'Shuri', 47),
    (NULL, 'Quicksilver', 48),
    (NULL, 'Scarlet Witch', 48),
    (NULL, 'Vision', 49),
    (NULL, 'Ultron', 49),
    (NULL, 'Ant-Man', 50),
    (NULL, 'Wasp', 50),
    (NULL, 'Hank Pym', 51),
    (NULL, 'Janet van Dyne', 51),
    (NULL, 'Namor', 52),
    (NULL, 'Aquaman', 52),
    (NULL, 'Green Goblin', 53),
    (NULL, 'Venom', 53),
    (NULL, 'Daredevil', 54),
    (NULL, 'Punisher', 54),
    (NULL, 'Kingpin', 55),
    (NULL, 'Electro', 55),
    (NULL, 'Kraven the Hunter', 56),
    (NULL, 'Black Cat', 56),
    (NULL, 'Red Skull', 57),
    (NULL, 'Baron Zemo', 57),
    (NULL, 'Ghost Rider', 58),
    (NULL, 'Blade', 58),
    (NULL, 'Luke Cage', 59),
    (NULL, 'Jessica Jones', 59),
    (NULL, 'Iron Fist', 60),
    (NULL, 'Moon Knight', 60),
    (NULL, 'Elektra', 61),
    (NULL, 'Bullseye', 61),
    (NULL, 'Yondu', 62),
    (NULL, 'Star-Lord', 62),
    (NULL, 'Gamora', 63),
    (NULL, 'Drax', 63),
    (NULL, 'Rocket', 64),
    (NULL, 'Groot', 64),
    (NULL, 'Nebula', 65),
    (NULL, 'Mantis', 65),
    (NULL, 'Kang the Conqueror', 66),
    (NULL, 'Doctor Doom', 66),
    (NULL, 'Apocalypse', 67),
    (NULL, 'Sinister', 67);